services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Esites\EncryptionBundle\Helper\EncryptionHelper:
    arguments:
      $encryptionKeyFile: '%esites_encryption_bundle.encryption_key_file%'
    public: true

  Esites\EncryptionBundle\Provider\UserProvider:
    arguments:
      $usernameField: '%esites_encryption_bundle.username_field%'
      $userClass: '%esites_encryption_bundle.user_class%'

  Esites\EncryptionBundle\EventListener\EncryptionListener:
    tags:
      - { name: doctrine.event_listener, event: prePersist, priority: -999999999 }
      - { name: doctrine.event_listener, event: preUpdate, priority: -999999999 }
      - { name: doctrine.event_listener, event: postLoad, priority: 999999999 }

  Esites\EncryptionBundle\EventListener\HashListener:
    tags:
      - { name: doctrine.event_listener, event: prePersist, priority: -999999998 }
      - { name: doctrine.event_listener, event: preUpdate, priority: -999999998 }
